### ISSUE TITLE
add 3 videos

### ISSUE THREAD

**Issue by knopf127** [epexa/sweely.org#7]
add an English version of the video to all the Landing's languages except Russian Landing.
add to the blocks: sponsors, NPO, volunteers, accordingly. 
place the videos to the right of the text, over the background image.
make it as a youtube player (screenshot) + up. 
place a big play button, and add an arrow.
When you click on the video, it should be opened in the modal window of youtube player.

**Comment by k1r1k1** [comment]
@knopf127 hi! Resolved by this [commit](https://github.com/epexa/sweely.org/commit/d6e32f61ac7a4f5c5dc04f7d2cc25a3f0799cad0)
